apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: perl:5
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - [""]
          restartPolicy: OnFailure
