apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: pod-resources
spec:
  containers:
  - name: pod1
    image: nginx:1.16
    resources:
      requests:
        memory: "50Mi"
        cpu: "40m"
      limits:
        memory: "50Mi"
        cpu: "40m"

